wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719225040
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      3:
      - 23
      4: 3.12.4
      5: 0.17.2
      6: 4.41.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
